version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - npm_default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app 
    networks:
      - npm_default
    depends_on:
      - db
   

  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - npm_default
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - npm_default

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "8090:81"
    volumes:
      - ./letsencrypt:/etc/letsencrypt  # Mount local letsencrypt directory
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - npm_default


networks:
  npm_default:
    external: true

volumes:
  postgres_data:
  npm_data:
  npm_letsencrypt:
  